url: https://leviathan-avc.github.io
baseurl: 

# Site settings
title: Leviathan-AVC
email: public@leviathan-avc.com
description: "Leviathan-AVC (Audio, Visual, Computers) is a consulting business specializing in entertainment and related activities."


# Team names, titles and social links
people:
- name: Thomas Vecchione
  pic: 1
  position: Owner/Primary Consulatant
  social:
    - title: google-plus
      url: https://plus.google.com/+ThomasVecchione
    - title: github
      url: https://github.com/Seablade

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/leviathan-avc

# Postal address (add as many lines as necessary)
address:
  - line: 170 Clarks Lane
  - line: Aylett, VA. 23009

# Build settings
markdown: kramdown
permalink: pretty
